In [1]:
import sys
sys.path.append('..')
from src.utils import section

import pandas as pd

In [2]:
from src.data_load import data_loader
# Load dataset
df = data_loader('../data/processed/cleaned_ecommerce_data.csv')
df.head()

,cart_value_usd,past_return_rate,size_bracketing_flag,delivery_days_taken,discount_pct_applied,product_category,fit_review_sentiment,newsletter_subscriber,browser_used,checkout_device,packaging_color,loyalty_card_color,return_risk_label
0,172.17,0.233,1,11,10,Footwear,True-to-Size,1,Safari,Android-App,Kraft-Brown,Platinum,1
1,213.55,0.235,1,6,40,Accessories,True-to-Size,0,Firefox,Android-App,Branded-Teal,Silver,0
2,371.70,0.461,1,11,40,Formal-Eveningwear,True-to-Size,0,Firefox,iOS-App,Kraft-Brown,Gold,1
3,317.18,0.080,0,1,20,Footwear,Inconsistent-Sizing,0,Firefox,iOS-App,Kraft-Brown,Gold,1
4,152.68,0.133,0,3,40,Accessories,True-to-Size,0,Edge,iOS-App,Branded-Teal,Silver,0

In [3]:
# Check class imbalance
df['return_risk_label'].value_counts(normalize=True)

return_risk_label
1    0.645506
0    0.354494
Name: proportion, dtype: float64

In [4]:
from src.pipeline import pipeline_builder

preprocessor = pipeline_builder(df, ["size_bracketing_flag", "newsletter_subscriber", "return_risk_label"])
transformed_df = pd.DataFrame(preprocessor.fit_transform(df), columns=preprocessor.get_feature_names_out())
section("transformed dataset", 45)
transformed_df.head()

=============================================
TRANSFORMED DATASET:

,num_transformer__cart_value_usd,num_transformer__past_return_rate,num_transformer__delivery_days_taken,num_transformer__discount_pct_applied,cat_transformer__product_category_Accessories,cat_transformer__product_category_Casual-Tops,cat_transformer__product_category_Footwear,cat_transformer__product_category_Formal-Eveningwear,cat_transformer__fit_review_sentiment_Inconsistent-Sizing,cat_transformer__fit_review_sentiment_Runs-Slightly-Small,...,cat_transformer__checkout_device_iOS-App,cat_transformer__packaging_color_Branded-Teal,cat_transformer__packaging_color_Kraft-Brown,cat_transformer__packaging_color_Minimal-White,cat_transformer__loyalty_card_color_Gold,cat_transformer__loyalty_card_color_Platinum,cat_transformer__loyalty_card_color_Silver,remainder__size_bracketing_flag,remainder__newsletter_subscriber,remainder__return_risk_label
0,-0.556792,-0.318873,1.576552,-0.804104,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0
1,-0.215863,-0.306282,0.008070,0.933992,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
2,1.087129,1.116451,1.576552,0.933992,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
3,0.637940,-1.282050,-1.560411,-0.224739,0.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,-0.717369,-0.948401,-0.933018,0.933992,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0