In [1]:
# Libraries
import sys
sys.path.append("..")

import pandas as pd

In [2]:
from src.data_load import data_loader

# Load data
df = data_loader("../data/raw/influencer_campaign_regression.csv")
df.head()

,creator_followers_k,engagement_rate_pct,paid_boost_spend_usd,avg_watch_time_sec,promo_discount_pct,content_format,audience_intent_tier,caption_word_count,hashtags_used_count,creator_phone_os,contract_payment_terms,posting_day_weather,campaign_revenue_usd
0,425.4,2.14,1331.0,35.2,10,Static-Carousel,High-Intent-Niche,35,16,Android,Net-30,Sunny,15192.26
1,171.3,5.73,3925.0,25.4,10,YouTube-Deep-Dive,Lifestyle-Warm,26,16,Android,Upfront,Cloudy,20018.44
2,356.4,8.03,1817.0,9.4,0,Short-Video-Reel,High-Intent-Niche,43,24,Android,Upfront,Cloudy,21146.87
3,272.2,7.70,942.0,32.1,15,Short-Video-Reel,Lifestyle-Warm,113,9,Android,Net-15,Rainy,17639.62
4,143.0,6.06,3347.0,51.0,20,Short-Video-Reel,Broad-Entertainment,72,18,Android,Net-30,Cloudy,17375.60

In [3]:
from src.pipeline import pipeline_builder

preprocessor = pipeline_builder(df, ['campaign_revenue_usd'])

transformed_df = pd.DataFrame(preprocessor.fit_transform(df), columns=preprocessor.get_feature_names_out())
transformed_df.head()

,num_transformer__creator_followers_k,num_transformer__engagement_rate_pct,num_transformer__paid_boost_spend_usd,num_transformer__avg_watch_time_sec,num_transformer__promo_discount_pct,num_transformer__caption_word_count,num_transformer__hashtags_used_count,cat_transformer__content_format_Short-Video-Reel,cat_transformer__content_format_Static-Carousel,cat_transformer__content_format_YouTube-Deep-Dive,...,cat_transformer__audience_intent_tier_Lifestyle-Warm,cat_transformer__creator_phone_os_Android,cat_transformer__creator_phone_os_iOS,cat_transformer__contract_payment_terms_Net-15,cat_transformer__contract_payment_terms_Net-30,cat_transformer__contract_payment_terms_Upfront,cat_transformer__posting_day_weather_Cloudy,cat_transformer__posting_day_weather_Rainy,cat_transformer__posting_day_weather_Sunny,remainder__campaign_revenue_usd
0,1.522316,-1.189859,-0.774871,0.348784,-0.273849,-1.206693,0.519348,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,15192.26
1,-0.483936,0.223913,1.262589,-0.344042,-0.273849,-1.416310,0.519348,0.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,20018.44
2,0.977525,1.129672,-0.393142,-1.475187,-1.435045,-1.020367,1.662972,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,21146.87
3,0.312722,0.999715,-1.080411,0.129624,0.306749,0.609985,-0.481323,1.0,0.0,0.0,...,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,17639.62
4,-0.707379,0.353870,0.808599,1.465789,0.887347,-0.344936,0.805254,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,17375.60